"""Inspection views the owner can read without running code.

Every report is plain Markdown or CSV written to a directory the owner can open
in any editor. Nothing here is generated by a model: the reports are a rendering
of rows that already exist, so a report and the database can be compared line by
line.
"""

from __future__ import annotations

import csv
import json
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from . import db


def _stamp(value: Any) -> str:
    if value is None:
        return "-"
    try:
        moment = datetime.fromtimestamp(int(value) / 1000, tz=timezone.utc)
    except (TypeError, ValueError, OSError, OverflowError):
        return str(value)
    return moment.strftime("%Y-%m-%d %H:%M:%SZ")


def _escape(text: Any) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def _table(headers: list[str], rows: list[list[Any]]) -> list[str]:
    lines = ["| " + " | ".join(headers) + " |"]
    lines.append("| " + " | ".join("---" for _ in headers) + " |")
    for row in rows:
        lines.append("| " + " | ".join(_escape(cell) for cell in row) + " |")
    if not rows:
        lines.append("| " + " | ".join("-" for _ in headers) + " |")
    return lines


def overview(connection: sqlite3.Connection) -> dict[str, Any]:
    counts_by_status = {
        str(row["retention_status"]): int(row["n"])
        for row in connection.execute(
            "SELECT retention_status, COUNT(*) AS n FROM nodes GROUP BY retention_status"
        ).fetchall()
    }
    counts_by_type = {
        str(row["node_type"]): int(row["n"])
        for row in connection.execute(
            "SELECT node_type, COUNT(*) AS n FROM nodes GROUP BY node_type"
        ).fetchall()
    }
    counts_by_origin = {
        str(row["origin_class"]): int(row["n"])
        for row in connection.execute(
            "SELECT origin_class, COUNT(*) AS n FROM nodes GROUP BY origin_class"
        ).fetchall()
    }
    counts_by_edge = {
        str(row["edge_type"]): int(row["n"])
        for row in connection.execute(
            "SELECT edge_type, COUNT(*) AS n FROM edges GROUP BY edge_type"
        ).fetchall()
    }
    findings = {
        f"{row['kind']}:{row['status']}": int(row["n"])
        for row in connection.execute(
            "SELECT kind, status, COUNT(*) AS n FROM findings GROUP BY kind, status"
        ).fetchall()
    }
    admissions = {
        str(row["decision"]): int(row["n"])
        for row in connection.execute(
            "SELECT decision, COUNT(*) AS n FROM admission_log GROUP BY decision"
        ).fetchall()
    }
    trace_row = connection.execute(
        "SELECT COUNT(*) AS n, MAX(created_at) AS latest FROM traces"
    ).fetchone()
    return {
        "rule_version": str(db.active_rules(connection)["version"]),
        "nodes_by_status": counts_by_status,
        "nodes_by_type": counts_by_type,
        "nodes_by_origin": counts_by_origin,
        "edges_by_type": counts_by_edge,
        "findings": findings,
        "admissions": admissions,
        "traces": int(trace_row["n"] or 0),
        "latest_trace_at": trace_row["latest"],
        "pending_owner_confirmations": int(
            connection.execute(
                "SELECT COUNT(*) AS n FROM nodes WHERE owner_confirmation = 'pending'"
            ).fetchone()["n"]
        ),
    }


def brief(connection: sqlite3.Connection) -> str:
    """A compact per-turn context block. Bounded by the reporting rules."""
    rules = db.active_rules(connection)
    limit = int(rules["reporting"]["brief_max_chars"])
    summary = overview(connection)
    open_conflicts = summary["findings"].get("conflict:open", 0)
    open_duplicates = summary["findings"].get("duplicate:open", 0)
    open_outdated = summary["findings"].get("outdated:open", 0)
    open_gaps = summary["findings"].get("gap:open", 0)
    quarantined = summary["nodes_by_status"].get("quarantined", 0)
    retention_queue = summary["nodes_by_status"].get("dormant", 0) + summary[
        "nodes_by_status"
    ].get("archived", 0)
    lines = [
        "MEMORY MAP STATUS",
        f"rules {summary['rule_version']}",
        f"nodes active {summary['nodes_by_status'].get('active', 0)} "
        f"reinforced {summary['nodes_by_status'].get('reinforced', 0)} "
        f"quarantined {quarantined} retention-queue {retention_queue}",
        f"open findings conflict {open_conflicts} duplicate {open_duplicates} "
        f"outdated {open_outdated} gap {open_gaps}",
        f"owner confirmations pending {summary['pending_owner_confirmations']}",
        f"traces recorded {summary['traces']}",
    ]
    if open_conflicts or summary["pending_owner_confirmations"]:
        lines.append("action: run `map audit` and show the owner the open items")
    text = "\n".join(lines)
    return text[:limit]


def node_history(connection: sqlite3.Connection, node_id: str) -> dict[str, Any]:
    node = db.fetch_node(connection, node_id)
    if node is None:
        return {"status": "not-found", "node_id": node_id}
    history = db.rows_to_dicts(
        connection.execute(
            "SELECT * FROM node_history WHERE node_id = ? ORDER BY at, seq", (node_id,)
        ).fetchall()
    )
    edges = db.rows_to_dicts(
        connection.execute(
            """
            SELECT edge_type, src_id, dst_id, confidence, confidence_basis,
                   captured_by, evidence_json, recorded_at
            FROM edges WHERE src_id = ? OR dst_id = ?
            ORDER BY edge_type, recorded_at
            """,
            (node_id, node_id),
        ).fetchall()
    )
    traces = db.rows_to_dicts(
        connection.execute(
            """
            SELECT t.id AS trace_id, t.created_at, t.query, tc.returned,
                   tc.drop_reason, tc.final_score
            FROM trace_candidates AS tc
            JOIN traces AS t ON t.id = tc.trace_id
            WHERE tc.node_id = ?
            ORDER BY t.created_at DESC
            LIMIT 20
            """,
            (node_id,),
        ).fetchall()
    )
    findings = db.rows_to_dicts(
        connection.execute(
            "SELECT id, kind, status, detail FROM findings "
            "WHERE subject_ids_json LIKE ? ORDER BY kind",
            (f"%{node_id}%",),
        ).fetchall()
    )
    return {
        "status": "ok",
        "node": dict(node),
        "history": history,
        "edges": edges,
        "recent_traces": traces,
        "findings": findings,
    }


def render_node_history(connection: sqlite3.Connection, node_id: str) -> str:
    detail = node_history(connection, node_id)
    if detail["status"] != "ok":
        return f"# Node {node_id}\n\nNot found in this map.\n"
    node = detail["node"]
    lines = [
        f"# Node {node_id}",
        "",
        f"- Type: {node['node_type']}",
        f"- Retention status: {node['retention_status']}",
        f"- Origin class: {node['origin_class']} (session kind {node['session_kind']})",
        f"- Captured by: {node['captured_by']}",
        f"- Source reference: {node['source_ref'] or '-'}",
        f"- Confidence: {node['confidence']} ({node['confidence_basis']})",
        f"- Owner confirmation: {node['owner_confirmation']}",
        f"- Use count: {node['use_count']}, last used {_stamp(node['last_used_at'])}",
        f"- Recorded at: {_stamp(node['recorded_at'])}",
        f"- Observed at: {_stamp(node['observed_at'])}",
        f"- Valid from: {_stamp(node['valid_from'])}, valid to: {_stamp(node['valid_to'])}",
        f"- Superseded by: {node['superseded_by'] or '-'}",
        f"- Rule version: {node['rule_version']}",
        "",
        "## Content",
        "",
        "```text",
        str(node["content"]) or "(tombstone: content removed)",
        "```",
        "",
        "## Lifecycle history",
        "",
    ]
    lines += _table(
        ["When", "Transition", "From", "To", "Actor", "Accepted", "Reason"],
        [
            [
                _stamp(row["at"]),
                row["transition"],
                row["from_status"] or "-",
                row["to_status"] or "-",
                row["actor"],
                "yes" if row["accepted"] else "no",
                row["reason"],
            ]
            for row in detail["history"]
        ],
    )
    lines += ["", "## Edges", ""]
    lines += _table(
        ["Type", "Source", "Target", "Confidence", "Basis", "Captured by"],
        [
            [
                row["edge_type"],
                row["src_id"],
                row["dst_id"],
                row["confidence"],
                row["confidence_basis"],
                row["captured_by"],
            ]
            for row in detail["edges"]
        ],
    )
    lines += ["", "## Recent retrievals that considered this node", ""]
    lines += _table(
        ["When", "Trace", "Query", "Returned", "Score", "Drop reason"],
        [
            [
                _stamp(row["created_at"]),
                row["trace_id"],
                row["query"],
                "yes" if row["returned"] else "no",
                round(float(row["final_score"]), 4),
                row["drop_reason"] or "-",
            ]
            for row in detail["recent_traces"]
        ],
    )
    lines += ["", "## Findings naming this node", ""]
    lines += _table(
        ["Finding", "Kind", "Status", "Detail"],
        [[row["id"], row["kind"], row["status"], row["detail"]] for row in detail["findings"]],
    )
    lines.append("")
    return "\n".join(lines)


def render_conflicts(connection: sqlite3.Connection) -> str:
    rows = connection.execute(
        "SELECT * FROM findings WHERE kind = 'conflict' AND status = 'open' "
        "ORDER BY score DESC, id"
    ).fetchall()
    lines = ["# Open conflicts", ""]
    if not rows:
        lines += ["No open conflicts.", ""]
        return "\n".join(lines)
    for row in rows:
        subjects = json.loads(str(row["subject_ids_json"]))
        lines += [
            f"## {row['id']}",
            "",
            f"- Detail: {row['detail']}",
            f"- Score: {round(float(row['score']), 4)}",
            f"- Detector: {row['detector_version']}",
            f"- First seen: {_stamp(row['created_at'])}, "
            f"last seen: {_stamp(row['updated_at'])}",
            "",
        ]
        for subject in subjects:
            node = db.fetch_node(connection, subject)
            if node is None:
                lines.append(f"- `{subject}` (node no longer present)")
                continue
            lines.append(
                f"- `{subject}` [{node['retention_status']}/{node['origin_class']}] "
                f"{_escape(node['content'])}"
            )
        lines.append("")
    return "\n".join(lines)


def render_retention_queue(connection: sqlite3.Connection) -> str:
    rows = connection.execute(
        """
        SELECT id, node_type, retention_status, origin_class, use_count,
               last_used_at, created_at, owner_confirmation, quarantine_reason, content
        FROM nodes
        WHERE retention_status IN ('dormant', 'archived', 'quarantined', 'superseded')
           OR owner_confirmation = 'pending'
        ORDER BY retention_status, last_used_at IS NULL DESC, last_used_at, id
        """
    ).fetchall()
    lines = ["# Retention queue", "", f"{len(rows)} node(s) awaiting a decision.", ""]
    lines += _table(
        [
            "Node",
            "Type",
            "Status",
            "Origin",
            "Uses",
            "Last used",
            "Owner confirmation",
            "Quarantine reason",
            "Content",
        ],
        [
            [
                row["id"],
                row["node_type"],
                row["retention_status"],
                row["origin_class"],
                row["use_count"],
                _stamp(row["last_used_at"]),
                row["owner_confirmation"],
                row["quarantine_reason"] or "-",
                (str(row["content"])[:120] or "(tombstone)"),
            ]
            for row in rows
        ],
    )
    lines.append("")
    return "\n".join(lines)


def render_traces(connection: sqlite3.Connection, limit: int | None = None) -> str:
    rules = db.active_rules(connection)
    count = int(limit if limit is not None else rules["reporting"]["trace_report_limit"])
    traces = connection.execute(
        "SELECT * FROM traces ORDER BY created_at DESC, id LIMIT ?", (count,)
    ).fetchall()
    lines = ["# Recent retrieval traces", "", f"Showing the last {len(traces)} trace(s).", ""]
    for trace in traces:
        lanes = json.loads(str(trace["lanes_json"]))
        lane_summary = ", ".join(
            f"{name}={'on' if detail.get('available') else 'off'}"
            for name, detail in sorted(lanes.items())
        )
        lines += [
            f"## {trace['id']}",
            "",
            f"- When: {_stamp(trace['created_at'])}",
            f"- Query: `{_escape(trace['query'])}`",
            f"- Lanes: {lane_summary}",
            f"- Completeness: {trace['completeness']} (source {trace['trace_source']})",
            f"- Candidates: {trace['candidate_count']}, returned {trace['returned_count']}",
            f"- Rule version: {trace['rule_version']}",
            "",
        ]
        rows = connection.execute(
            """
            SELECT tc.*, n.content FROM trace_candidates AS tc
            LEFT JOIN nodes AS n ON n.id = tc.node_id
            WHERE tc.trace_id = ? ORDER BY tc.rank
            """,
            (trace["id"],),
        ).fetchall()
        lines += _table(
            [
                "Rank",
                "Node",
                "Lanes",
                "Keyword",
                "Vector",
                "Graph",
                "Recency",
                "Importance",
                "Trust",
                "Final",
                "Returned",
                "Drop reason",
            ],
            [
                [
                    row["rank"],
                    row["node_id"],
                    row["lane_hits"] or "-",
                    round(float(row["keyword_score"]), 4),
                    round(float(row["vector_score"]), 4),
                    round(float(row["graph_score"]), 4),
                    round(float(row["recency_score"]), 4),
                    round(float(row["importance_mult"]), 4),
                    round(float(row["trust_mult"]), 4),
                    round(float(row["final_score"]), 4),
                    "yes" if row["returned"] else "no",
                    row["drop_reason"] or "-",
                ]
                for row in rows
            ],
        )
        lines.append("")
    return "\n".join(lines)


def render_overview(connection: sqlite3.Connection) -> str:
    summary = overview(connection)
    lines = [
        "# Memory map overview",
        "",
        f"- Active rule version: {summary['rule_version']}",
        f"- Traces recorded: {summary['traces']} "
        f"(latest {_stamp(summary['latest_trace_at'])})",
        f"- Owner confirmations pending: {summary['pending_owner_confirmations']}",
        "",
        "## Nodes by retention status",
        "",
    ]
    lines += _table(
        ["Status", "Count"], sorted(summary["nodes_by_status"].items())
    )
    lines += ["", "## Nodes by type", ""]
    lines += _table(["Type", "Count"], sorted(summary["nodes_by_type"].items()))
    lines += ["", "## Nodes by origin class", ""]
    lines += _table(["Origin", "Count"], sorted(summary["nodes_by_origin"].items()))
    lines += ["", "## Edges by type", ""]
    lines += _table(["Edge type", "Count"], sorted(summary["edges_by_type"].items()))
    lines += ["", "## Findings", ""]
    lines += _table(["Kind and status", "Count"], sorted(summary["findings"].items()))
    lines += ["", "## Admission decisions", ""]
    lines += _table(["Decision", "Count"], sorted(summary["admissions"].items()))
    lines.append("")
    return "\n".join(lines)


def write_csv(connection: sqlite3.Connection, table: str, destination: Path) -> int:
    allowed = {"nodes", "edges", "findings", "traces", "trace_candidates", "admission_log"}
    if table not in allowed:
        raise ValueError(f"table {table!r} is not exportable")
    rows = connection.execute(f"SELECT * FROM {table}").fetchall()
    destination.parent.mkdir(parents=True, exist_ok=True)
    with destination.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        if rows:
            writer.writerow(rows[0].keys())
            for row in rows:
                writer.writerow(list(row))
        else:
            cursor = connection.execute(f"SELECT * FROM {table} LIMIT 0")
            writer.writerow([column[0] for column in cursor.description or []])
    return len(rows)


def write_all(connection: sqlite3.Connection, out_dir: str | Path) -> dict[str, str]:
    directory = Path(out_dir)
    directory.mkdir(parents=True, exist_ok=True)
    written: dict[str, str] = {}
    documents = {
        "map-overview.md": render_overview(connection),
        "conflicts.md": render_conflicts(connection),
        "retention-queue.md": render_retention_queue(connection),
        "traces.md": render_traces(connection),
    }
    for name, body in documents.items():
        target = directory / name
        target.write_text(body, encoding="utf-8")
        written[name] = target.as_posix()
    for table in ("nodes", "edges", "findings", "traces", "trace_candidates"):
        target = directory / f"{table}.csv"
        write_csv(connection, table, target)
        written[f"{table}.csv"] = target.as_posix()
    return written
